const fs = require('fs');
const path = require('path');

const BASE = String.raw`c:\Users\teste\aa\lecreuset`;
const IMG = 'https://www.lecreuset.com.br/dw/image/v2/BDRT_PRD/on/demandware.static/-/Sites-le-creuset-br-master/default';

const PRODUCTS = [
  {file:'panela-redonda-signature-foret.html',title:'Panela Redonda Signature Forêt 28 cm',subtitle:'Ferro Fundido Esmaltado · Forêt',price:'R$ 3.429,00',installments:'10x R$ 342,90 sem juros',pix:'R$ 3.257,55 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'A panela redonda icônica da Le Creuset em sua versão mais popular. O ferro fundido esmaltado distribui e retém calor de forma uniforme, ideal para cozimento lento. Pronta para uso sem pré-tempero, com interior esmaltado na cor areia que resiste a odores e sabores. 15 artesãos especializados inspecionam manualmente cada peça produzida na França desde 1925.',specs:[['Material','Ferro Fundido Esmaltado'],['Cor','Forêt'],['Capacidade','6,7 L'],['Tamanho','28 cm'],['Dimensões','37,7 × 29,7 × 18,4 cm'],['Fontes de calor','Vitrocerâmico, Indução, Elétrico, Gás'],['Origem','França'],['Garantia','Vitalícia'],['Limpeza','Lavagem à mão']],images:[IMG+'/dw5cb33aa8/images/21177240984450-panela-redonda-foret.jpg?sw=650&sh=650&sm=fit',IMG+'/dw400cfa84/images/21177240984450-panela-redonda-foret-1.jpg?sw=650&sh=650&sm=fit',IMG+'/dw4357ddb9/images/21177240984450-panela-redonda-foret-2.jpg?sw=650&sh=650&sm=fit',IMG+'/dw01fb5b90/images/21177240984450-panela-redonda-foret-3.jpg?sw=650&sh=650&sm=fit']},
  {file:'panela-oval-signature-foret.html',title:'Panela Oval Signature Forêt 31 cm',subtitle:'Ferro Fundido Esmaltado · Forêt',price:'R$ 3.399,00',installments:'10x R$ 339,90 sem juros',pix:'R$ 3.229,05 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'A panela oval icônica da Le Creuset em ferro fundido esmaltado. O formato oval é especialmente adequado para cortes maiores de carne, aves inteiras e pães ovais. Distribuição de calor superior com retenção excepcional que preserva umidade e sabor.',specs:[['Material','Ferro Fundido Esmaltado'],['Cor','Forêt'],['Capacidade','6,3 L'],['Tamanho','31 cm'],['Dimensões','40,4 × 25,7 × 17,9 cm'],['Fontes de calor','Vitrocerâmico, Indução, Elétrico, Gás'],['Forno','Até 260°C'],['Origem','França'],['Garantia','Vitalícia'],['Limpeza','Lavagem à mão']],images:[IMG+'/dw1047b189/images/21178310984450-panela-oval.jpg?sw=650&sh=650&sm=fit']},
  {file:'cacarola-buffet-signature-foret.html',title:'Caçarola Buffet Signature Forêt 30 cm',subtitle:'Ferro Fundido Esmaltado · Forêt',price:'R$ 2.999,00',installments:'10x R$ 299,90 sem juros',pix:'R$ 2.849,05 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'Caçarola de ferro fundido esmaltado com distribuição e retenção de calor excepcionais. Vai do forno direto à mesa de forma elegante. Pronta para uso sem tempero, resiste a manchas e lascas. Tampa hermética circula vapor e devolve umidade aos alimentos.',specs:[['Material','Ferro Fundido Esmaltado'],['Cor','Forêt'],['Capacidade','3,5 L'],['Porções','6-8 pessoas'],['Tamanho','30 cm'],['Dimensões','40,2 × 31,7 × 13,5 cm'],['Fontes de calor','Indução, Gás, Elétrico, Forno'],['Origem','França'],['Garantia','Vitalícia'],['Limpeza','Lava-louças ou mão']],images:[IMG+'/dw913d8b67/images/21180300984450-cacarola-buffet-foret.png?sw=650&sh=650&sm=fit']},
  {file:'panela-redonda-signature-foret-20cm.html',title:'Panela Redonda Signature Forêt 20 cm',subtitle:'Ferro Fundido Esmaltado · Forêt',price:'R$ 2.329,00',installments:'10x R$ 232,90 sem juros',pix:'R$ 2.212,55 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'A panela redonda icônica Le Creuset em versão compacta, ideal para 2-3 pessoas. O mesmo desempenho excepcional do ferro fundido esmaltado: distribuição uniforme de calor e retenção superior. Perfeita para molhos, porções individuais e receitas menores.',specs:[['Material','Ferro Fundido Esmaltado'],['Cor','Forêt'],['Capacidade','2,4 L'],['Tamanho','20 cm'],['Dimensões','27,3 × 21,5 × 14,1 cm'],['Fontes de calor','Vitrocerâmico, Indução, Elétrico, Gás'],['Origem','França'],['Garantia','Vitalícia'],['Limpeza','Lavagem à mão']],images:[IMG+'/dw5cb33aa8/images/21177240984450-panela-redonda-foret.jpg?sw=650&sh=650&sm=fit',IMG+'/dw400cfa84/images/21177240984450-panela-redonda-foret-1.jpg?sw=650&sh=650&sm=fit']},
  {file:'travessa-retangular-san-francisco-foret.html',title:'Travessa Retangular com Tampa San Francisco Forêt 31 cm',subtitle:'Cerâmica · Forêt',price:'R$ 1.199,00',installments:'10x R$ 119,90 sem juros',pix:'R$ 1.139,05 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'Travessa retangular de cerâmica com tampa da coleção San Francisco na exclusiva cor Forêt. Com 4L de capacidade, é perfeita para servir e armazenar com elegância. Vai ao forno, micro-ondas e congelador. A tampa veda os aromas e preserva a umidade dos alimentos.',specs:[['Material','Cerâmica'],['Cor','Forêt'],['Capacidade','4 L'],['Tamanho','31 cm'],['Dimensões','40,9 × 25,4 × 13,45 cm'],['Fontes de calor','Forno, Micro-ondas, Congelador'],['Origem','Tailândia'],['Garantia','10 anos'],['Limpeza','Lava-louças ou mão']],images:[IMG+'/dw553d597a/images/71025310980280-travessa-retagular-com-tampa-san.jpg?sw=650&sh=650&sm=fit',IMG+'/dw865d4887/images/71025310980280-travessa-retagular-com-tampa-san-1.jpg?sw=650&sh=650&sm=fit',IMG+'/dw148edb42/images/71025310980280-travessa-retagular-com-tampa-san-2.jpg?sw=650&sh=650&sm=fit']},
  {file:'travessa-quadrada-san-francisco-foret.html',title:'Travessa Quadrada com Tampa San Francisco Forêt',subtitle:'Cerâmica · Forêt',price:'R$ 899,00',installments:'9x R$ 99,89 sem juros',pix:'R$ 854,05 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'Travessa quadrada de cerâmica com tampa da coleção San Francisco na cor Forêt. Com 2,9L de capacidade, ideal para servir e armazenar com elegância. Tampa inclusa para preservar aromas e umidade. Combina funcionalidade com o design assinado da Le Creuset.',specs:[['Material','Cerâmica'],['Cor','Forêt'],['Capacidade','2,9 L'],['Dimensões','33,3 × 25,3 × 13,3 cm'],['Fontes de calor','Forno, Micro-ondas, Congelador'],['Origem','Tailândia'],['Garantia','10 anos'],['Limpeza','Lava-louças ou mão']],images:[IMG+'/dw62754017/images/71026230980280-travessa-quadrada-com-tampa-san-francisco.jpg?sw=650&sh=650&sm=fit',IMG+'/dw0d9ae26e/images/71026230980280-travessa-quadrada-com-tampa-san-francisco-1.jpg?sw=650&sh=650&sm=fit',IMG+'/dwa0d4ac53/images/71026230980280-travessa-quadrada-com-tampa-san-francisco-2.jpg?sw=650&sh=650&sm=fit',IMG+'/dw6af506b8/images/71026230980280-travessa-quadrada-com-tampa-san-francisco-3.jpg?sw=650&sh=650&sm=fit']},
  {file:'chaleira-classica-foret.html',title:'Chaleira Clássica Forêt',subtitle:'Aço Carbono Esmaltado · Forêt',price:'R$ 929,00',installments:'9x R$ 103,22 sem juros',pix:'R$ 882,55 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'Adicione um toque clássico à sua cozinha com a Chaleira Clássica da Le Creuset na exclusiva cor Forêt. Feita em aço carbono esmaltado para ferver água rapidamente. Apito de tom único avisa quando a água ferve. Inclui marcações internas de nível e alça resistente ao calor.',specs:[['Material','Aço Carbono Esmaltado'],['Cor','Forêt'],['Capacidade','1,6 L'],['Porções','6 xícaras'],['Dimensões','26,4 × 20,9 × 25,1 cm'],['Fontes de calor','Vitrocerâmico, Indução, Elétrico, Gás'],['Origem','Tailândia'],['Garantia','5 anos'],['Limpeza','Lavagem à mão']],images:[IMG+'/dw05492d65/images/40104010981000-chaleira-classica-foret.jpg?sw=650&sh=650&sm=fit',IMG+'/dwf61f32b8/images/40104010981000-chaleira-classica-foret-1.jpg?sw=650&sh=650&sm=fit']},
  {file:'chaleira-kone-foret.html',title:'Chaleira Kone Forêt',subtitle:'Aço Carbono Esmaltado · Forêt',price:'R$ 839,00',installments:'8x R$ 104,88 sem juros',pix:'R$ 797,05 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'A Chaleira Kone é feita com Aço Carbono Esmaltado que possibilita ferver água rapidamente. Possui apito de tom único indicando quando a água ferve, marcações internas e base generosa. Compatível com todas as fontes de calor incluindo indução. Design moderno e icônico.',specs:[['Material','Aço Carbono Esmaltado'],['Cor','Forêt'],['Capacidade','1,6 L'],['Dimensões','25,2 × 20 × 24 cm'],['Fontes de calor','Vitrocerâmico, Indução, Elétrico, Gás'],['Origem','Tailândia'],['Garantia','5 anos'],['Limpeza','Lavagem à mão']],images:[IMG+'/dwebf93040/images/40125600982300-chaleira-kone-foret.jpg?sw=650&sh=650&sm=fit',IMG+'/dw181a64f0/images/40125600982300-chaleira-kone-foret-1.jpg?sw=650&sh=650&sm=fit',IMG+'/dwacb02a63/images/40125600982300-chaleira-kone-foret2.jpg?sw=650&sh=650&sm=fit']},
  {file:'moedor-sal-foret.html',title:'Moedor de Sal 21 cm Forêt',subtitle:'Acessórios · Forêt',price:'R$ 369,00',installments:'3x R$ 123,00 sem juros',pix:'R$ 350,55 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'Moedor de sal premium com mecanismo de moagem cerâmica ajustável. Controle o tamanho da granulação via pino superior ajustável, do fino ao grosso. Ideal para uso à mesa, churrascos e aplicações com sal grosso. Combine com o Moedor de Pimenta Forêt.',specs:[['Material','Plástico ABS'],['Mecanismo','Cerâmica ajustável'],['Cor','Forêt'],['Dimensões','6,1 × 6,1 × 20,6 cm'],['Origem','China'],['Garantia','10 anos'],['Limpeza','Pano seco ou escova']],images:[IMG+'/dw8a52997b/images/44002210985200-moedor-foret.jpg?sw=650&sh=650&sm=fit',IMG+'/dwa6a9c05d/images/44002210985200-moedor-sal.jpg?sw=650&sh=650&sm=fit']},
  {file:'moedor-pimenta-foret.html',title:'Moedor de Pimenta 21 cm Forêt',subtitle:'Acessórios · Forêt',price:'R$ 369,00',installments:'3x R$ 123,00 sem juros',pix:'R$ 350,55 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'Moedor de pimenta que combina sofisticação e praticidade. Sistema de moagem cerâmica ajustável do fino ao grosso. Exterior em plástico ABS resistente a odores e fácil de limpar. Design ergonômico para o dia a dia e ocasiões especiais. Combine com o Moedor de Sal Forêt.',specs:[['Material','Plástico ABS'],['Mecanismo','Cerâmica ajustável'],['Cor','Forêt'],['Dimensões','6,1 × 6,1 × 20,6 cm'],['Origem','China'],['Garantia','10 anos'],['Limpeza','Pano seco ou escova']],images:[IMG+'/dw8a52997b/images/44002210985200-moedor-foret.jpg?sw=650&sh=650&sm=fit',IMG+'/dw94398809/images/44001210985200-moedor-pimenta.jpg?sw=650&sh=650&sm=fit']},
  {file:'caneca-200ml-foret.html',title:'Caneca London 200ml Forêt',subtitle:'Cerâmica · Forêt',price:'R$ 139,00',installments:'em até 1x sem juros',pix:'R$ 132,05 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'A Caneca London é perfeita para café, chá e chocolate quente. Cerâmica premium com superfície esmaltada para fácil limpeza e higiene. Vai ao forno, micro-ondas e congelador. O formato clássico e a cor Forêt trazem elegância ao momento do seu café.',specs:[['Material','Cerâmica'],['Cor','Forêt'],['Capacidade','200 ml'],['Dimensões','10,7 × 7,8 × 7,8 cm'],['Fontes de calor','Forno, Micro-ondas, Congelador'],['Origem','Tailândia'],['Garantia','10 anos'],['Limpeza','Lava-louças ou mão']],images:[IMG+'/dw75fddb92/images/70303200980099-caneca-foret-200ml.jpg?sw=650&sh=650&sm=fit']},
  {file:'ramekin-200ml-foret.html',title:'Ramekin 200ml Forêt',subtitle:'Cerâmica · Forêt',price:'R$ 139,00',installments:'em até 1x sem juros',pix:'R$ 132,05 no PIX (5% OFF)',badge:'LANÇAMENTO',desc:'De bolos a gratinados e tortas, tudo fica mais saboroso no Ramekin Le Creuset. Superfície esmaltada para fácil desenformagem e excelente retenção de calor. Borda interna permite empilhamento sem grudar. Vai ao forno, micro-ondas e congelador.',specs:[['Material','Cerâmica'],['Cor','Forêt'],['Capacidade','200 ml'],['Dimensões','9,3 × 9,3 × 5,6 cm'],['Fontes de calor','Forno, Micro-ondas, Congelador'],['Origem','Tailândia'],['Garantia','10 anos'],['Limpeza','Lava-louças ou mão']],images:[IMG+'/dw8f850e0f/images/70403200980099-mini-cocotte.jpg?sw=650&sh=650&sm=fit']},
];

const tmpl = fs.readFileSync(path.join(BASE, '_prod_tmpl.html'), 'utf8');

function makeThumbs(images) {
  if (images.length <= 1) return '';
  const items = images.map((u, i) =>
    `<div class="${i===0?'thumb active':'thumb'}" onclick="setImg(this,'${u}')"><img src="${u}" alt="" /></div>`
  ).join('\n');
  return `<div class="gallery-thumbs">${items}</div>`;
}

function makeSpecs(sl) {
  const rows = sl.map(([k,v]) => `<tr><td class="spec-key">${k}</td><td class="spec-val">${v}</td></tr>`).join('\n');
  return `<table class="spec-table">${rows}</table>`;
}

let count = 0;
for (const p of PRODUCTS) {
  let html = tmpl;
  html = html.replaceAll('{{TITLE}}', p.title);
  html = html.replaceAll('{{SUBTITLE}}', p.subtitle);
  html = html.replaceAll('{{PRICE}}', p.price);
  html = html.replaceAll('{{INSTALLMENTS}}', p.installments);
  html = html.replaceAll('{{PIX}}', p.pix);
  html = html.replaceAll('{{BADGE}}', p.badge);
  html = html.replaceAll('{{DESC}}', p.desc);
  html = html.replaceAll('{{SPECS}}', makeSpecs(p.specs));
  html = html.replaceAll('{{THUMBS}}', makeThumbs(p.images));
  html = html.replaceAll('{{IMG0}}', p.images[0]);
  fs.writeFileSync(path.join(BASE, p.file), html, 'utf8');
  console.log('OK:', p.file);
  count++;
}
console.log(`\nTotal: ${count} páginas criadas`);
